// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/konto/models"
)

type AddMoneyToGoalInput struct {
	GoalID    string  `json:"goalId"`
	Amount    float64 `json:"amount"`
	AccountID string  `json:"accountId"`
}

type AddMoneyToUserInput struct {
	UserID string  `json:"userId"`
	Amount float64 `json:"amount"`
}

type AuthPayload struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}

type ContributeToSharedBudgetInput struct {
	SharedBudgetID string  `json:"sharedBudgetId"`
	AccountID      string  `json:"accountId"`
	Amount         float64 `json:"amount"`
	Description    *string `json:"description,omitempty"`
}

type CreateBudgetInput struct {
	CategoryID  string              `json:"categoryId"`
	LimitAmount float64             `json:"limitAmount"`
	Period      models.BudgetPeriod `json:"period"`
}

type CreateCategoryInput struct {
	Name string `json:"name"`
}

type CreateGoalInput struct {
	Name         string  `json:"name"`
	TargetAmount float64 `json:"targetAmount"`
}

type CreateSharedBudgetInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type CreateTransactionInput struct {
	AccountID   string                 `json:"accountId"`
	CategoryID  string                 `json:"categoryId"`
	Amount      float64                `json:"amount"`
	Type        models.TransactionType `json:"type"`
	Description *string                `json:"description,omitempty"`
}

type CreateUserInput struct {
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
	Role     models.Role `json:"role"`
}

type InviteToSharedBudgetInput struct {
	SharedBudgetID string  `json:"sharedBudgetId"`
	InviteeID      string  `json:"inviteeId"`
	Message        *string `json:"message,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type RegisterInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RespondToInvitationInput struct {
	InvitationID string `json:"invitationId"`
	Accept       bool   `json:"accept"`
}

type TransactionConnection struct {
	Edges      []*TransactionEdge `json:"edges"`
	PageInfo   *PageInfo          `json:"pageInfo"`
	TotalCount int                `json:"totalCount"`
}

type TransactionEdge struct {
	Node   *models.Transaction `json:"node"`
	Cursor string              `json:"cursor"`
}

type TransactionFilter struct {
	StartDate  *string                 `json:"startDate,omitempty"`
	EndDate    *string                 `json:"endDate,omitempty"`
	CategoryID *string                 `json:"categoryId,omitempty"`
	Type       *models.TransactionType `json:"type,omitempty"`
}

type TransferBetweenAccountsInput struct {
	FromAccountID string  `json:"fromAccountId"`
	ToAccountID   string  `json:"toAccountId"`
	Amount        float64 `json:"amount"`
}

type UpdateSharedBudgetInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}
